p = Player(name="Tyler")
p.save()
p = Player(name="Kaighn")
p.save()
p = Player(name="Will")
p.save()
p = Player(name="Jorge")
p.save()
p = Player(name="Shaunak")
p.save()
p = Player(name="Jonah")
p.save()
p = Player(name="James")
p.save()
p = Player(name="Henry")
p.save()
p = Player(name="Adil")
p.save()
p = Player(name="Kaustav")
p.save()
p = Player(name="Mehul")
p.save()
p = Player(name="Jeremy")
p.save()
p = Player(name="Emma")
p.save()
p = Player(name="Brian")
p.save()
p = Player(name="Austin")
p.save()
p = Player(name="Eddie")
p.save()
p = Player(name="Scoots")
p.save()
p = Player(name="Madison")
p.save()
p = Player(name="AaronK")
p.save()
p = Player(name="Abhi")
p.save()
p = Player(name="Aleis")
p.save()
p = Player(name="AlexG")
p.save()
p = Player(name="Allen")
p.save()
p = Player(name="Amy")
p.save()
p = Player(name="Andrew")
p.save()
p = Player(name="Anna")
p.save()
p = Player(name="Anthony")
p.save()
p = Player(name="Archit")
p.save()
p = Player(name="Ari")
p.save()
p = Player(name="Ashley")
p.save()
p = Player(name="Asim")
p.save()
p = Player(name="AustinP")
p.save()
p = Player(name="BHo")
p.save()
p = Player(name="Becki")
p.save()
p = Player(name="BenG")
p.save()
p = Player(name="Braden")
p.save()
p = Player(name="Brendan")
p.save()
p = Player(name="Brendon")
p.save()
p = Player(name="Bressler")
p.save()
p = Player(name="Bri")
p.save()
p = Player(name="Brigitte")
p.save()
p = Player(name="Brooks")
p.save()
p = Player(name="Cahill")
p.save()
p = Player(name="Callan")
p.save()
p = Player(name="Callista")
p.save()
p = Player(name="Carmen")
p.save()
p = Player(name="Carolyn")
p.save()
p = Player(name="Cassidee")
p.save()
p = Player(name="Cat")
p.save()
p = Player(name="Catherine")
p.save()
p = Player(name="Chad")
p.save()
p = Player(name="Charlie")
p.save()
p = Player(name="Charlotte")
p.save()
p = Player(name="Chris")
p.save()
p = Player(name="Clive")
p.save()
p = Player(name="Corinne")
p.save()
p = Player(name="Daniel")
p.save()
p = Player(name="DanielR")
p.save()
p = Player(name="Danielle")
p.save()
p = Player(name="DannyO")
p.save()
p = Player(name="David")
p.save()
p = Player(name="Dawson")
p.save()
p = Player(name="Dee")
p.save()
p = Player(name="Diego")
p.save()
p = Player(name="DillonG")
p.save()
p = Player(name="Duncan")
p.save()
p = Player(name="Dustin")
p.save()
p = Player(name="EJ")
p.save()
p = Player(name="Ebor")
p.save()
p = Player(name="Edward")
p.save()
p = Player(name="Elizabeth")
p.save()
p = Player(name="Emily")
p.save()
p = Player(name="EmilyH")
p.save()
p = Player(name="Emmanuel")
p.save()
p = Player(name="Eric")
p.save()
p = Player(name="Erin")
p.save()
p = Player(name="Ethan")
p.save()
p = Player(name="Eva")
p.save()
p = Player(name="GJ")
p.save()
p = Player(name="Gaines")
p.save()
p = Player(name="Gautam")
p.save()
p = Player(name="Gene")
p.save()
p = Player(name="GeorgeC")
p.save()
p = Player(name="GeorgeT")
p.save()
p = Player(name="Georgia")
p.save()
p = Player(name="Grant")
p.save()
p = Player(name="Hafferkamp")
p.save()
p = Player(name="Haigreev")
p.save()
p = Player(name="Harper")
p.save()
p = Player(name="Hunter")
p.save()
p = Player(name="Isa")
p.save()
p = Player(name="Iza")
p.save()
p = Player(name="Jaclyn")
p.save()
p = Player(name="JacobR")
p.save()
p = Player(name="Jake")
p.save()
p = Player(name="Jamie")
p.save()
p = Player(name="Jasmine")
p.save()
p = Player(name="Jasper")
p.save()
p = Player(name="Jennie")
p.save()
p = Player(name="Jenny")
p.save()
p = Player(name="Johnell")
p.save()
p = Player(name="Jon")
p.save()
p = Player(name="Jonathan")
p.save()
p = Player(name="Jordan")
p.save()
p = Player(name="JoshQ")
p.save()
p = Player(name="Julie")
p.save()
p = Player(name="Juntoku")
p.save()
p = Player(name="Justin")
p.save()
p = Player(name="Kassra")
p.save()
p = Player(name="Kat")
p.save()
p = Player(name="Katie")
p.save()
p = Player(name="Katsis")
p.save()
p = Player(name="Ken")
p.save()
p = Player(name="Kevin")
p.save()
p = Player(name="Kristen")
p.save()
p = Player(name="Kunal")
p.save()
p = Player(name="Kyla")
p.save()
p = Player(name="KyleO")
p.save()
p = Player(name="Lasko")
p.save()
p = Player(name="Laubster")
p.save()
p = Player(name="Laura")
p.save()
p = Player(name="Lefko")
p.save()
p = Player(name="Leslie")
p.save()
p = Player(name="Lide")
p.save()
p = Player(name="Linda")
p.save()
p = Player(name="Maddie")
p.save()
p = Player(name="Mahsa")
p.save()
p = Player(name="Malcolm")
p.save()
p = Player(name="Manish")
p.save()
p = Player(name="McKayla")
p.save()
p = Player(name="McKenzie")
p.save()
p = Player(name="Meade")
p.save()
p = Player(name="Meron")
p.save()
p = Player(name="MeronZ")
p.save()
p = Player(name="Method")
p.save()
p = Player(name="Michael")
p.save()
p = Player(name="Michaela")
p.save()
p = Player(name="Miguel")
p.save()
p = Player(name="Mike")
p.save()
p = Player(name="Miles")
p.save()
p = Player(name="Milu")
p.save()
p = Player(name="Natalie")
p.save()
p = Player(name="Negatu")
p.save()
p = Player(name="Neil")
p.save()
p = Player(name="Nicholas")
p.save()
p = Player(name="Nicolas")
p.save()
p = Player(name="Nihir")
p.save()
p = Player(name="Nikhil")
p.save()
p = Player(name="Nikki")
p.save()
p = Player(name="Nishad")
p.save()
p = Player(name="Noah")
p.save()
p = Player(name="NoahL")
p.save()
p = Player(name="Olivia")
p.save()
p = Player(name="PeterYom")
p.save()
p = Player(name="Philippa")
p.save()
p = Player(name="Pooja")
p.save()
p = Player(name="Pranava")
p.save()
p = Player(name="Rafay")
p.save()
p = Player(name="Raiyan")
p.save()
p = Player(name="Raj")
p.save()
p = Player(name="Rebecca")
p.save()
p = Player(name="Rechel")
p.save()
p = Player(name="Rhino")
p.save()
p = Player(name="Richard")
p.save()
p = Player(name="Rishi")
p.save()
p = Player(name="Rob")
p.save()
p = Player(name="Safkat")
p.save()
p = Player(name="Sagar")
p.save()
p = Player(name="Sam")
p.save()
p = Player(name="SamCor")
p.save()
p = Player(name="Sammy")
p.save()
p = Player(name="Sarah")
p.save()
p = Player(name="SarahG")
p.save()
p = Player(name="SarahJ")
p.save()
p = Player(name="Schroeder")
p.save()
p = Player(name="Seamus")
p.save()
p = Player(name="Semester")
p.save()
p = Player(name="Shane")
p.save()
p = Player(name="Shannon")
p.save()
p = Player(name="Shashi")
p.save()
p = Player(name="Shauna")
p.save()
p = Player(name="Shibs")
p.save()
p = Player(name="Siva")
p.save()
p = Player(name="Sludwig")
p.save()
p = Player(name="Solomon")
p.save()
p = Player(name="Stacy")
p.save()
p = Player(name="Steven")
p.save()
p = Player(name="Stoner")
p.save()
p = Player(name="TJ")
p.save()
p = Player(name="Tara")
p.save()
p = Player(name="Ting")
p.save()
p = Player(name="Tyrone")
p.save()
p = Player(name="Udit")
p.save()
p = Player(name="Vaibhav")
p.save()
p = Player(name="Victoria")
p.save()
p = Player(name="Vignesh")
p.save()
p = Player(name="Vikram")
p.save()
p = Player(name="Vinay")
p.save()
p = Player(name="Walle")
p.save()
p = Player(name="William")
p.save()
p = Player(name="Yara")
p.save()
p = Player(name="Zach")
p.save()
p = Player(name="Zohaib")
p.save()
p = Player(name="Mithun")
p.save()
p = Player(name="Jacob")
p.save()
p = Player(name="Jason")
p.save()
p = Player(name="Murphy")
p.save()
p = Player(name="Sanford")
p.save()
p = Player(name="MattyP")
p.save()
p = Player(name="Lyon")
p.save()
p = Player(name="Ben")
p.save()
p = Player(name="Bryce")
p.save()
p = Player(name="Josh")
p.save()
p = Player(name="Alex")
p.save()
p = Player(name="Lizzie")
p.save()
p = Player(name="Nick")
p.save()
p = Player(name="Sahil")
p.save()
p = Player(name="Rachel")
p.save()
p = Player(name="Sachin")
p.save()
p = Player(name="PapaBear")
p.save()
p = Player(name="Yitaek")
p.save()
p = Player(name="Graeme")
p.save()
p = Player(name="Suyash")
p.save()